# Generated by Django 4.1 on 2022-09-13 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("Active", "active"), ("Inactive", "inactive")],
                        db_index=True,
                        default="draft",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        db_index=True, max_length=1000, verbose_name="Body"
                    ),
                ),
                ("like_count", models.IntegerField(verbose_name="Like_count")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Datetime"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated Datetime"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="items.item"
                    ),
                ),
            ],
            options={"db_table": "review",},
        ),
    ]
